const mongoose = require('mongoose');

const courtSchema = new mongoose.Schema({
    //court id auto-generated by MongoDB as _id
    name: {type: String, required: true, unique: true},
    location: {
        address: {type: String, required: true},
        coordinates: { lat: Number, lng: Number}
     }, //used for google maps integration
    description: String,
    type: {type:String, enum: ['indoor', 'outdoor'], required: true},
    totalCourts: {type: Number, default: 1},
    rates: {
        weekday: {type: Number},
        weedend: {type: Number}
     },
    ownerId: {type:mongoose.Schema.Types.ObjectId, ref: 'User', required: true}, // Owner reference
    averageRating: {type: Number, default: 0}, // Calculated from reviews
});

module.exports = mongoose.model('Court', courtSchema);
