const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    //user id auto-generated by MongoDB as _id
    username: { type: String, required: true, unique: true },
    password: { type: String, required: true }, //password will be hased via bcrypt
    role: { type: String, enum: ['player', 'owner', 'employee'], default: 'player' },
    bio: { type: String, default: "" },

    //if owner/employee, link to court; if player, can be null
    courtId: { type: mongoose.Schema.Types.ObjectId, ref: 'Court' }, 
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('User', userSchema);